### ISSUE TITLE
Request to support third party packages in worker threads

### ISSUE THREAD

**Issue by johnfung95** [jpwallace22/use-react-workers#17]
Hi, I came across your package and tried to use the worker function.
However, I received the following error when running.
`ReferenceError: moment__WEBPACK_IMPORTED_MODULE_0___default is not defined`

Any idea on the resolution?

**Comment by johnfung95** [comment]
I suspect the problem is related to the usage of third-party library because I am currently adopting moment js in the build. Is it a bug? I am unsure, but I guess one workaround is to abandon third-party package usage when using the useWorkerFunc?

**Comment by jpwallace22** [comment]
@johnfung95  A snippet of the use code would help me deduce more of what is going on in this use case. But from what you are describing, it sounds like you are attempting to load a third party resource into the web worker. This won't work because of restrictions with the worker thread. 

I am currently (slowly) working on a way to transport third party resources.

**Comment by johnfung95** [comment]
@jpwallace22 thanks for your reply. There is not too much going on in my program, basically just a function call with the moment js and return a value. But the code always stops in the moment js usage line.

`import moment from "moment";`
`const dates = moment().utc().format("YYYY-MM-DD");`                <======= error in here

where it becomes `moment__WEBPACK_IMPORTED_MODULE_0___default().utc().format("YYYY-MM-DD");` from the source code panel in the browser. That's why raising the aforementioned undefined error.

By the way, I tested my program without the moment js and it works just fine. Therefore it is very likely due to the restriction of using third-party resources in the worker thread (as you mentioned).

I think I can find a workaround for my problem. 
Thank you for your effort and progress in maintaining this repo. 🙏

**Comment by jpwallace22** [comment]
@johnfung95 I'm working on the docs to transfer third-party resources over to worker as well. I'm ging to switch this over to a feature request, and hopefully I can hop on it soon!

**Comment by Rushclin** [comment]
Same error
