### ISSUE TITLE
can you explain more about useWorkerState

### ISSUE THREAD

**Issue by frommainland** [jpwallace22/use-react-workers#18]
How can you get the current state value of the heavy compute function, running, completed or error?

**Comment by jpwallace22** [comment]
@frommainland 
Sorry, I don't think the docs are linked in the README, but [here](https://jpwallace22.github.io/use-react-workers/hooks/useworkerstate/) you can see interface for `useWorkerState`

The `Controller` interface is index 2 in the return. 

The return is 
```
[T, Setter, Controller]
```

And this is the `Controller` interface: 
```
interface Controller {
  status: 'idle' | 'running' | 'error' | 'expired' | 'killed';
  terminate: () => void;
}
```
