### ISSUE TITLE
ReferenceError: useWorkerFunc is not defined

### ISSUE THREAD

**Issue by ceu** [jpwallace22/use-react-workers#22]

**Comment by ceu** [comment]
![Uploading 截屏2024-05-09 16.48.48.png…]()

**Comment by ceu** [comment]
![截屏2024-05-09 16 48 48](https://github.com/jpwallace22/use-react-workers/assets/13114273/e8328e83-82e6-4807-9264-6a6b47ca6133)

**Comment by ceu** [comment]
@jpwallace22

**Comment by jpwallace22** [comment]
@ceu I am unable to duplicate this behavior. Do you have a more in depth description of how you got to this state?

**Comment by jpwallace22** [comment]
Closing due to lack of information

**Comment by Gwened** [comment]
I also got the issue.

When entering 'use-react-workers' (F12 in VS Code), I see this index.d.ts: 
```
export * from './useWorkerFunc.ts';
export * from './useWorkerState.ts';
export * from './useWorker.ts';
export * from './types.ts';
```

and the Typescript error says:
`An import path cannot end with a '.ts' extension. Consider importing './useWorkerFunc' instead. ts(2691)`

Now if I delete the occurrences of ".ts", both errors disappear.
